databases:
  - name: cicd_test
    databaseName: cicd_test_production
    user: postgresql
    plan: free

services:
  - type: web
    name: cicd_test
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cicd_test
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
